dataset:
  name: BIMProveKITTI
  dataset_path:
  cache_dir: ./logs/cache

model:
  name: PointPillars
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"
  point_cloud_range: [-4.1, -4.1, -3.2, 4.1, 4.1, 5.7] #[x_min, y_min, z_min, x_max, y_max, z_max]
  classes: ['net', 'barrier']
  npoint: 250000
  score_thres: 0.1

  loss:
    focal: #loss_cls
      gamma: 2.0
      alpha: 0.25
      loss_weight: 1.0
    smooth_l1: #loss_bbox
      beta: 0.31
      loss_weight: 1.0
    cross_entropy: #loss_dir
      loss_weight: 1.0

  voxelize:
    max_num_points: 24
    voxel_size: &vsize
      [0.051, 0.051, 8.9] #voxel edge lengths with format [x, y, z]. - learns fast, goes to overfitting fast
      #max_voxels: [26000, 60000] #The maximum number of voxels. May be a tuple with values for training and testing.
      # X-Y dims are 8.2 x 8.2
      #Voxelsize of 0.001 x 0.001 yields to 8200 x 8200 voxels, 67240000
      #             0.01 x 0.01 yields to 820 x 820 voxels, 672400
      #             0.1 x 0.1 yields to 82 x 82 voxels, 6724
      # 26000 voxels would mean ca. 160 x 160 voxels i.e. ca 0.05125   
    max_voxels: [26000, 60000] #The maximum number of voxels. May be a tuple with values for training and testing.

  voxel_encoder:
    in_channels: 4
    feat_channels: [64]
    voxel_size: *vsize

  scatter:
    in_channels: 64
    output_shape: [496, 432]

  backbone:
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    layer_strides: [2, 2, 2]

  neck:
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [1, 2, 4]
    use_conv_for_no_stride: false

  head:
    in_channels: 384
    feat_channels: 384
    nms_pre: 100
    score_thr: 0.1
    ranges: [
      [-4.1, -4.1, 4.3, 4.1, 4.1, 4.3],
      [-4.1, -4.1, 1.3, 4.1, 4.1, 1.3],
      [-4.7, -4.7, 0.5, 4.7, 4.7, 0.5]
    ]
    sizes: [[2.6, 2.8, 1.73], [0.6, 1.76, 1.73], [3.9, 2.0, 1.56]]
    rotations: [0, 1.57]
    iou_thr: [[0.35, 0.5]]

  augment:
    PointShuffle: True
    ObjectRangeFilter:
      point_cloud_range: [-4.1, -4.1, -3.2, 4.1, 4.1, 5.7]
    ObjectSample:
      min_points_dict:
        net: 5
        barrier: 5
      sample_dict:
        net: 5
        barrier: 5

pipeline:
  name: ObjectDetection
  test_compute_metric: true
  batch_size: 1
  val_batch_size: 1
  test_batch_size: 1
  save_ckpt_freq: 5
  max_epoch: 50
  main_log_dir: ./logs
  train_sum_dir: ./logs/train_log
  grad_clip_norm: 100
  num_workers: 0
  pin_memory: true

  optimizer:
    lr: 0.0001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [0.1]
  difficulties: [0]
  summary:
    record_for: []
    max_pts: 250000
    use_reference: false
    max_outputs: 1
